spring:
  application:
    name: SpringAI
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      model: gpt-4

  datasource:
    url: jdbc:postgresql://localhost:5432/futsalytics
    username: testuser
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
